name: E2E Test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  server_build:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: Go mod tidy
      run: go mod tidy
    
    - name: Build go binaries
      shell: bash
      run: GOOS='linux' GOARCH='amd64' CGO_ENABLED=0 go build -o zenith_server server/main.go
    
    - name: Upload zenith_server binary
      uses: actions/upload-artifact@v4
      with:
        name: zenith_server
        path: zenith_server
        retention-days: 1

  client_build:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'

    - name: Go mod tidy
      run: go mod tidy
    
    - name: Build go binaries
      shell: bash
      run: GOOS='linux' GOARCH='amd64' CGO_ENABLED=0 go build -o zenith_client client/main.go
    
    - name: Upload zenith_client binary
      uses: actions/upload-artifact@v4
      with:
        name: zenith_client
        path: zenith_client
        retention-days: 1

  start_server:
    needs: 
      - server_build
      - client_build
    runs-on: ubuntu-22.04
    env:
      SYSTEM_NAME: server
    
    steps:
    
    - name: Download server binary
      uses: actions/download-artifact@v4
      with:
        name: zenith_server
    
    - name: Download client binary
      uses: actions/download-artifact@v4
      with:
        name: zenith_client
    
    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: ${{ env.SYSTEM_NAME }}

    - name: Server up
      shell: bash
      run: |
        chmod +x ./zenith_server
        ./zenith_server 8080 &
    
    - name: Add service
      run: |
        curl -X POST http://0.0.0.0:8080/add \
            -H "Content-Type: application/json" \
            -d '{"service_name": "main_service"}' \
            -i
    
    - name: Check
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://0.0.0.0:8080 check
  
  ping_on_server:
    needs: 
      - server_build
      - client_build
    runs-on: ubuntu-22.04
    steps:
    
    - name: Download client binary
      uses: actions/download-artifact@v4
      with:
        name: zenith_client
    
    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: test

    - name: Ping
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://server:8080 ping --until 360
  
  client01:
    needs: [ping_on_server]
    runs-on: ubuntu-22.04
    env:
      SYSTEM_NAME: client-01
    
    steps:
    - name: Download client binary
      uses: actions/download-artifact@v4
      with:
        name: zenith_client
    
    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: ${{ env.SYSTEM_NAME }}
    
    - name: Add service
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://server:8080 add client01_service
    
    - name: Check
      shell: bash
      run: |
        ./zenith_client --url http://server:8080 check client01_service

  client02:
    needs: [ping_on_server]
    runs-on: ubuntu-22.04
    env:
      SYSTEM_NAME: client-02
    
    steps:
    - name: Download client binary
      uses: actions/download-artifact@v4
      with:
        name: zenith_client
    
    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: ${{ env.SYSTEM_NAME }}
    
    - name: Add service
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://server:8080 add client_02
    
    - name: Check
      shell: bash
      run: |
        ./zenith_client --url http://server:8080 check client_02

  shutdown_system:
    needs: [ping_on_server]
    runs-on: ubuntu-22.04
    env:
      SYSTEM_NAME: server
    steps:
    
    - name: Download client binary
      uses: actions/download-artifact@v4
      with:
        name: zenith_client

    - uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        tags: tag:ci
        retry: 3
        hostname: ${{ env.SYSTEM_NAME }}

    - name: Sleep to simulate load
      shell: bash
      run: sleep 10
    
    - name: Terminate client-01
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://server:8080 remove client01_service

    - name: Sleep to simulate load
      shell: bash
      run: sleep 12

    - name: Terminate client-02
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://server:8080 remove client_02
    
    - name: Sleep to simulate load
      shell: bash
      run: sleep 4

    - name: Terminate server
      shell: bash
      run: |
        chmod +x ./zenith_client
        ./zenith_client --url http://server:8080 remove main_service
